apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  selector:
    matchLabels:
      app: blue-deployment
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: blue-deployment
        tier: backend
        track: stable
    spec:
      containers:
        - name: blue-deployment
          image: nginx:1.14.2
          ports:
            - name: http
              containerPort: 80